name: im2latex
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pytorch-lightning=1.3.0
  - torchmetrics=0.3.1
  - smart_open
  - fastapi
  - uvicorn
  - editdistance
  - toml
  ## dev
  # wandb issue: https://discuss.pytorch.org/t/runtimeerror-module-backward-hook-for-grad-input-is-called-before-the-grad-output-one-this-happens-because-the-gradient-in-your-nn-m-odule-flows-to-the-modules-input-without-passing-through-the-modules-output/119763/8
  - wandb=0.10.20
  - jupyterlab
  - matplotlib
  # test
  - pytest
  - pytest-xdist
  # linter
  - pycodestyle
  - pylint
  - pydocstyle
  - mypy
  - bandit
  - safety
  # formatter
  - black
