name: im2latex
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch=1.8.1
  - torchvision=0.9.1
  - pytorch-lightning=1.3.0
  - torchmetrics=0.3.1
  - smart_open
  - fastapi
  - uvicorn
  - editdistance
  - toml
  ## dev
  - wandb
  - jupyterlab
  - matplotlib
  # test
  - pytest
  - pytest-xdist
  # linter
  - pycodestyle
  - pylint
  - pydocstyle
  - mypy
  - bandit
  - safety
  # formatter
  - black
